export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGIN_FAIL = 'AUTH_LOGIN_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const ACCOUNT_GET_ACCOUNT_SUCCESS = 'ACCOUNT_GET_ACCOUNT_SUCCESS'
export const ACCOUNT_GET_ACCOUNT_FAIL = 'ACCOUNT_GET_ACCOUNT_FAIL'

export const GET_APP_VERSION = 'GET_APP_VERSION'
